### ISSUE TITLE
Cannot find module ../app/router/middleware

### ISSUE THREAD

**Issue by jalateras** [spikebrehm/isomorphic-tutorial#14]
Error: Cannot find module './app/router/middleware'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jima/projects/reactjs/isomorphic-tutorial/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

It seems like you have forgotten to commit the file.

**Comment by adam-beck** [comment]
Fixed by ea83adeab84fd67f8ae34e9fe95cd9666367abe1

**Comment by rjbultitude** [comment]
This file seems to still be missing on the marked and moment branches
